adding section 2a running migrations with destroy and revert environments

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,7 +16,25 @@ commands:
             aws s3 rb s3://udapeople-${ID}
             aws cloudformation delete-stack  --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} 
             aws cloudformation delete-stack  --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
-  
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    steps:
+      - restore_cache:
+          key: backend-build
+          
+      - run:
+          name: Revert migrations
+          when: on_fail
+          command: |
+            # store result in SUCCESS if there was a successful migration associated with the workflow id
+            SUCCESS=`curl -H "token: 76f9514c-4cdd-4658-88f9-d7a705af6604" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}`
+            echo $SUCCESS
+            if [[ $SUCCESS == 1 ]];
+            then
+              cd ~/project/backend
+              npm install
+              npm run migrations:revert #revert the successful migration
+            fi 
             
 jobs:
   build-frontend:
@@ -211,6 +229,67 @@ jobs:
             
       # Here's where you will add some code to rollback on failure 
 
+  run-migrations:
+      docker:
+        # Docker image here that supports NodeJS
+        - image: circleci/node:13.8.0
+      steps:
+        # Checkout code from git
+        - checkout
+        - attach_workspace:
+            at: ~/
+        - restore_cache:
+            key: backend-build
+        - run:
+            name: Install AWS CLI dependencies
+            working_directory: /tmp
+            command: |
+              sudo apt-get update && sudo apt-get install -yy less
+              sudo apt-get install unzip -y
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+        # - run:
+        #     name: Install dependencies
+        #     command: |
+        #       curl -sL https://rpm.nodesource.com/setup_12.x | bash -
+        #       yum -y install nodejs npm tar gzip jq git
+        - run:
+            name: Run migrations
+            no_output_timeout: 20m
+            working_directory: ./backend
+            command: |
+              npm i
+              sudo npm install pm2 -g
+              echo ENVIRONMENT=production > ".env"
+              echo TYPEORM_CONNECTION=postgres >> ".env"
+              echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
+              echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
+              echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
+              echo NODE_ENV=production >> ".env"
+              echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
+              echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
+              echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
+              echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
+              echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
+              npm run migrations > migration.log
+              cat migration.log
+              migration_succesful=$(cat migration.log | grep -c "has been executed successfully")
+              if [ $migration_succesful > 0 ]; then exit 0; else exit 1; fi;
+        - run:
+            name: Send migration results to memstash
+            command: |
+              curl -H "Content-Type: text/plain" \
+                -H "token: 76f9514c-4cdd-4658-88f9-d7a705af6604" \
+                --request PUT --data "1" \
+                https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+        # Here's where you will add some code to rollback on failure
+        # - run:
+        #     name: Revert migrations
+        #     when: on_fail
+        - revert-migrations
+        - destroy-environment 
+
 workflows:
   default:
     jobs:
@@ -231,8 +310,8 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
