debugging run migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -230,59 +230,59 @@ jobs:
       # Here's where you will add some code to rollback on failure 
 
   run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
-      - image: circleci/node:13.8.0
-    steps:
-      # Checkout code from git
-      - checkout
-      - attach_workspace:
-          at: ~/
-      - restore_cache:
-          key: backend-build
-    - run:
-        name: prepare environment for backend build
-        command: |
-          echo "Preparing environment for backend build"
-          echo ENVIRONMENT=$ENVIRONMENT >> backend/.env
-          echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> backend/.env
-          echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> backend/.env
-          echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> backend/.env
-          echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> backend/.env
-          echo TYPEORM_HOST=$TYPEORM_HOST >> backend/.env
-          echo TYPEORM_PORT=$TYPEORM_PORT >> backend/.env
-          echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> backend/.env
-          echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> backend/.env
-          echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> backend/.env
-    - run:
-        name: Install dependencies
-        command: |
-          sudo apt update
-          sudo apt install -y awscli
-    - run:
-        name: Run migrations
-        command: |
-          cd backend
-          npm install
-          npm run build
-          npm run migrations:revert
-          npm run migrations > migration.log
-          cat migration.log
-          migration_succesful=$(cat migration.log | grep -c "has been executed successfully")
-          if [ $migration_succesful > 0 ]; then exit 0; else exit 1; fi;
-    - run:
-        name: Send migration results to memstash
-        command: |
-          curl -H "Content-Type: text/plain" \
-          -H "token: 76f9514c-4cdd-4658-88f9-d7a705af6604" \
-          --request PUT --data "1" \
-            https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-        # Here's where you will add some code to rollback on failure
-          # - run:
-          #     name: Revert migrations
-          #     when: on_fail
-          - revert-migrations
-          - destroy-environment 
+      docker:
+        # Docker image here that supports NodeJS
+        - image: circleci/node:13.8.0
+      steps:
+        # Checkout code from git
+        - checkout
+        - attach_workspace:
+            at: ~/
+        - restore_cache:
+            key: backend-build
+        - run:
+            name: prepare environment for backend build
+            command: |
+              echo "Preparing environment for backend build"
+              echo ENVIRONMENT=$ENVIRONMENT >> backend/.env
+              echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> backend/.env
+              echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> backend/.env
+              echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> backend/.env
+              echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> backend/.env
+              echo TYPEORM_HOST=$TYPEORM_HOST >> backend/.env
+              echo TYPEORM_PORT=$TYPEORM_PORT >> backend/.env
+              echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> backend/.env
+              echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> backend/.env
+              echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> backend/.env
+        - run:
+            name: Install dependencies
+            command: |
+              sudo apt update
+              sudo apt install -y awscli
+        - run:
+            name: Run migrations
+            command: |
+              cd backend
+              npm install
+              npm run build
+              npm run migrations:revert
+              npm run migrations > migration.log
+              cat migration.log
+              migration_succesful=$(cat migration.log | grep -c "has been executed successfully")
+              if [ $migration_succesful > 0 ]; then exit 0; else exit 1; fi;
+        - run:
+            name: Send migration results to memstash
+            command: |
+              curl -H "Content-Type: text/plain" \
+              -H "token: 76f9514c-4cdd-4658-88f9-d7a705af6604" \
+              --request PUT --data "1" \
+                https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            # Here's where you will add some code to rollback on failure
+              # - run:
+              #     name: Revert migrations
+              #     when: on_fail
+              - revert-migrations
+              - destroy-environment 
 
 workflows:
   default:
